/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Frame;
    import java.sql.Connection;
    import java.sql.DriverManager;
    import java.sql.Statement;
    import javax.swing.JOptionPane;
/**
 *
 * @author ACER
 */
public class forminput extends javax.swing.JFrame {
    Connection connect = null;
    Statement state = null;
    /**
     * Creates new form forminput
     */
    public forminput() {
        initComponents();
    }
    
    public void layarawal(){
        txtnama.setText("");
        txtnik.setText("");
        txtjenis.setText("");
        txtlahir.setText("");
        txttanggal.setText("");
        txtagama.setText("");
        txtpendidikan.setText("");
        txtpekerjaan.setText("");
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txtnama = new javax.swing.JTextField();
        txtnik = new javax.swing.JTextField();
        txtjenis = new javax.swing.JTextField();
        txtlahir = new javax.swing.JTextField();
        txtagama = new javax.swing.JTextField();
        txttanggal = new javax.swing.JTextField();
        txtpendidikan = new javax.swing.JTextField();
        txtpekerjaan = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        tombolSimpan = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(null);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("Nama");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(150, 10, 110, 20);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("NIK");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(150, 40, 100, 17);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setText("Jenis Kelamin");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(150, 70, 100, 17);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setText("Tempat Lahir");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(150, 100, 100, 17);

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setText("Tanggal Lahir");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(150, 130, 100, 17);

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setText("Pendidikan");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(150, 190, 100, 17);

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel8.setText("Pekerjaan");
        jPanel1.add(jLabel8);
        jLabel8.setBounds(150, 220, 100, 17);

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel9.setText("Agama");
        jPanel1.add(jLabel9);
        jLabel9.setBounds(150, 160, 100, 17);

        txtnama.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        txtnama.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtnamaActionPerformed(evt);
            }
        });
        jPanel1.add(txtnama);
        txtnama.setBounds(280, 10, 120, 30);

        txtnik.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jPanel1.add(txtnik);
        txtnik.setBounds(280, 40, 120, 30);

        txtjenis.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jPanel1.add(txtjenis);
        txtjenis.setBounds(280, 70, 120, 30);

        txtlahir.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jPanel1.add(txtlahir);
        txtlahir.setBounds(280, 100, 120, 30);

        txtagama.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jPanel1.add(txtagama);
        txtagama.setBounds(280, 160, 120, 30);

        txttanggal.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jPanel1.add(txttanggal);
        txttanggal.setBounds(280, 130, 120, 30);

        txtpendidikan.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jPanel1.add(txtpendidikan);
        txtpendidikan.setBounds(280, 190, 120, 30);

        txtpekerjaan.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jPanel1.add(txtpekerjaan);
        txtpekerjaan.setBounds(280, 220, 120, 30);

        jButton2.setText("Kembali");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2);
        jButton2.setBounds(170, 260, 100, 23);

        tombolSimpan.setText("Simpan");
        tombolSimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tombolSimpanActionPerformed(evt);
            }
        });
        jPanel1.add(tombolSimpan);
        tombolSimpan.setBounds(290, 260, 100, 23);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Frame/guiback.jpeg"))); // NOI18N
        jLabel1.setText("jLabel1");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(0, 0, 440, 300);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 437, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 294, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtnamaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtnamaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtnamaActionPerformed

    private void tombolSimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tombolSimpanActionPerformed
        try{
            if(txtnama.getText().equals("") || txtnik.getText().equals("") || txtjenis.getText().equals("")
                    || txtlahir.getText().equals("") || txttanggal.getText().equals("") || txtagama.getText().equals("") || 
                    txtpendidikan.getText().equals("") || txtpekerjaan.getText().equals("")){
                JOptionPane.showMessageDialog(this, "Data tidak boleh kosong","pesan",JOptionPane.ERROR_MESSAGE);
                layarawal();
            }else{
                Class.forName("com.mysql.jdbc.Driver");
                connect = DriverManager.getConnection("jdbc:mysql://localhost/datapenduduk","root","");
                state = connect.createStatement();
                String simpan = "insert into data values ('"+ txtnama.getText()+"','"+txtnik.getText()+"','"+txtjenis.getText()+"','"
                    +txtlahir.getText()+"','"+txttanggal.getText()+"','"+txtagama.getText()+"','"+txtpendidikan.getText()+"','"+txtpekerjaan.getText()+"')";
                state=connect.createStatement();
                int SA = state.executeUpdate(simpan);
                JOptionPane.showMessageDialog(this, "Data Tersimpan");
                this.setVisible(false);
                new formsukses().setVisible(true);
            }
        }catch(Exception e){
            JOptionPane.showMessageDialog(this, "Data sudah ada","pesan",JOptionPane.WARNING_MESSAGE);
            layarawal();
        }
    }//GEN-LAST:event_tombolSimpanActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        this.setVisible(false);
        new formawal().setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(forminput.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(forminput.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(forminput.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(forminput.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new forminput().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton tombolSimpan;
    private javax.swing.JTextField txtagama;
    private javax.swing.JTextField txtjenis;
    private javax.swing.JTextField txtlahir;
    private javax.swing.JTextField txtnama;
    private javax.swing.JTextField txtnik;
    private javax.swing.JTextField txtpekerjaan;
    private javax.swing.JTextField txtpendidikan;
    private javax.swing.JTextField txttanggal;
    // End of variables declaration//GEN-END:variables
}
